/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SetupMcpRouteImport } from './routes/setup-mcp'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OrgRouteImport } from './routes/org'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesNamespaceRouteImport } from './routes/sources.$namespace'
import { Route as BillingPlansRouteImport } from './routes/billing_.plans'
import { Route as SourcesAddPluginKeyRouteImport } from './routes/sources.add.$pluginKey'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMcpRoute = SetupMcpRouteImport.update({
  id: '/setup-mcp',
  path: '/setup-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNamespaceRoute = SourcesNamespaceRouteImport.update({
  id: '/sources/$namespace',
  path: '/sources/$namespace',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPlansRoute = BillingPlansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesAddPluginKeyRoute = SourcesAddPluginKeyRouteImport.update({
  id: '/sources/add/$pluginKey',
  path: '/sources/add/$pluginKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/connections': typeof ConnectionsRoute
  '/create-org': typeof CreateOrgRoute
  '/org': typeof OrgRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof ToolsRoute
  '/billing/plans': typeof BillingPlansRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/connections': typeof ConnectionsRoute
  '/create-org': typeof CreateOrgRoute
  '/org': typeof OrgRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof ToolsRoute
  '/billing/plans': typeof BillingPlansRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/connections': typeof ConnectionsRoute
  '/create-org': typeof CreateOrgRoute
  '/org': typeof OrgRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/setup-mcp': typeof SetupMcpRoute
  '/tools': typeof ToolsRoute
  '/billing_/plans': typeof BillingPlansRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/connections'
    | '/create-org'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing/plans'
    | '/sources/$namespace'
    | '/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/connections'
    | '/create-org'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing/plans'
    | '/sources/$namespace'
    | '/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/billing'
    | '/connections'
    | '/create-org'
    | '/org'
    | '/policies'
    | '/secrets'
    | '/setup-mcp'
    | '/tools'
    | '/billing_/plans'
    | '/sources/$namespace'
    | '/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BillingRoute: typeof BillingRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CreateOrgRoute: typeof CreateOrgRoute
  OrgRoute: typeof OrgRoute
  PoliciesRoute: typeof PoliciesRoute
  SecretsRoute: typeof SecretsRoute
  SetupMcpRoute: typeof SetupMcpRoute
  ToolsRoute: typeof ToolsRoute
  BillingPlansRoute: typeof BillingPlansRoute
  SourcesNamespaceRoute: typeof SourcesNamespaceRoute
  SourcesAddPluginKeyRoute: typeof SourcesAddPluginKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-mcp': {
      id: '/setup-mcp'
      path: '/setup-mcp'
      fullPath: '/setup-mcp'
      preLoaderRoute: typeof SetupMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$namespace': {
      id: '/sources/$namespace'
      path: '/sources/$namespace'
      fullPath: '/sources/$namespace'
      preLoaderRoute: typeof SourcesNamespaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/plans': {
      id: '/billing_/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof BillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/add/$pluginKey': {
      id: '/sources/add/$pluginKey'
      path: '/sources/add/$pluginKey'
      fullPath: '/sources/add/$pluginKey'
      preLoaderRoute: typeof SourcesAddPluginKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  BillingRoute: BillingRoute,
  ConnectionsRoute: ConnectionsRoute,
  CreateOrgRoute: CreateOrgRoute,
  OrgRoute: OrgRoute,
  PoliciesRoute: PoliciesRoute,
  SecretsRoute: SecretsRoute,
  SetupMcpRoute: SetupMcpRoute,
  ToolsRoute: ToolsRoute,
  BillingPlansRoute: BillingPlansRoute,
  SourcesNamespaceRoute: SourcesNamespaceRoute,
  SourcesAddPluginKeyRoute: SourcesAddPluginKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
